# W.A.P to input eight number from the user and display all the  unique number(once)
s = set() 
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))
num = input("enter num")
s.add(int(num))

print(s)